namespace Zapper.Core.Keyboard
{
    public enum Keycode
    {
        Esc = 1,
        Key1,
        Key2,
        Key3,
        Key4,
        Key5,
        Key6,
        Key7,
        Key8,
        Key9,
        Key0,
        Minus,
        Equal,
        Backspace,
        Tab,
        Q,
        W,
        E,
        R,
        T,
        Y,
        U,
        I,
        O,
        P,
        LeftBrace,
        RightBrace,
        Enter,
        LeftCtrl,
        A,
        S,
        D,
        F,
        G,
        H,
        J,
        K,
        L,
        Semicolon,
        Apostrophe,
        Grave,
        LeftShift,
        Backslash,
        Z,
        X,
        C,
        V,
        B,
        N,
        M,
        Comma,
        Dot,
        Slash,
        RightShift,
        KpAsterisk,
        LeftAlt,
        Space,
        Capslock,
        F1,
        F2,
        F3,
        F4,
        F5,
        F6,
        F7,
        F8,
        F9,
        F10,
        Numlock,
        ScrollLock,
        Kp7,
        Kp8,
        Kp9,
        KpMinus,
        Kp4,
        Kp5,
        Kp6,
        KpPlus,
        Kp1,
        Kp2,
        Kp3,
        Kp0,
        KpDot,
        Up = 103,
        Left = 105,
        Down = 108,
        Right = 106,
        KeyF11 = 87,
        KeyF12 = 88,
        Insert = 110,
        Delete = 111,
        RightCtrl = 97,
        RightAlt = 100,
        Super = 125
    }
}