name: Generate Coverage Badge

on:
  push:
    branches: [ main ]

jobs:
  coverage:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
        
    - name: Restore and test with coverage
      run: |
        dotnet restore src/zapper-next-gen.sln
        dotnet test src/zapper-next-gen.sln --configuration Release --collect:"XPlat Code Coverage" --results-directory ./coverage
      
    - name: Generate Coverage Badge
      uses: danielpalme/ReportGenerator-GitHub-Action@5.3.11
      with:
        reports: 'coverage/**/coverage.cobertura.xml'
        targetdir: 'coverage-report'
        reporttypes: 'Badges'
        
    - name: Upload coverage badge
      uses: actions/upload-artifact@v4
      with:
        name: coverage-badge
        path: coverage-report/badge_linecoverage.svg
        retention-days: 1