name: Generate Coverage Badge

on:
  push:
    branches: [ main ]

jobs:
  coverage:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
        
    - name: Restore and test with coverage
      run: |
        dotnet restore src/zapper-next-gen.sln
        dotnet test src/zapper-next-gen.sln --configuration Release --collect:"XPlat Code Coverage" --results-directory ./coverage
      
    - name: Generate Coverage Badge
      uses: danielpalme/ReportGenerator-GitHub-Action@5.3.11
      with:
        reports: 'coverage/**/coverage.cobertura.xml'
        targetdir: 'coverage-report'
        reporttypes: 'Badges'
        
    - name: Commit badge to coverage-badge branch
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        
        # Create or checkout the coverage-badge branch
        git fetch origin coverage-badge:coverage-badge || true
        git checkout coverage-badge || git checkout -b coverage-badge
        
        # Copy the badge
        cp coverage-report/badge_linecoverage.svg badge_linecoverage.svg
        
        # Commit and push
        git add badge_linecoverage.svg
        git commit -m "Update coverage badge" || echo "No changes to commit"
        git push origin coverage-badge --force